version: "3.8"

services:
  app:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres_db
      - redis
      - celery
  postgres_db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=protein_search
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  celery:
    build: ./app
    command: celery -A protein_project worker -l info
    volumes:
        - ./app/:/usr/src/app/
    depends_on:
        - postgres_db
        - redis

volumes:
  pgdata:



